name: Docker Build & Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build_image:
    name: Build da Imagem Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir e exportar a imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api_filmes:latest
          outputs: type=docker,dest=/tmp/api_filmes.tar

      - name: Upload do artefato (Salvar imagem)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/api_filmes.tar
          retention-days: 1

  publish_image:
    name: Publicação no DockerHub
    runs-on: ubuntu-latest
    needs: build_image
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download do artefato (Baixar imagem construída)
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Carregar e publicar a imagem
        run: |
          docker load --input /tmp/api_filmes.tar
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api_filmes:latest